### ISSUE TITLE
GraphTest

### ISSUE THREAD

**Issue by IbrayevRamil** [bmkodoo/javacourses2016#29]
There is a mistake in "exist-edge" test (in this data  {3, new Integer[][]{{4, 2}, {3, 2}, {2, 2}}, new Integer[][]{{2, 4}, {2, 2},{1,2}},new Boolean[]{false,true,false}},)  , edges {4,2} and {2,4} are the same in undirected graph, so result must be true,true,false

**Comment by nkarulin** [comment]
Just form a PR with fix, code tells more than words)
