### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by Yuhans** [bmkodoo/javacourses2016#37]
Из-за того, что требуемые результаты заданий воспринимаются людьми по разному, практически для каждого задания есть несколько тестов, которые ожидают различных результатов и требуют различных решений. Мне необходимо включить только нужные тесты для того, чтобы была заветная надпись **all checks have passed**, если нет, то чем руководствоваться?

**Comment by PutienkoEN** [comment]
Вообще лучше бы редактировали существующие, нежели новые создавать. Действительно, сейчас после мержа с мастером очень сложно собрать все в кучу(а еще кто-то с регистрами пошалил). Тесты взаимоисключающие, и просто не могут вернуть true оба. У себя я просто отключаю "неправильные" тесты и пишу в Issues.

**Comment by nkarulin** [comment]
Вообще было бы здорово собрать в мастере полноценный набор тестов на эти задачи, что бы переиспользовать его в будущем. Если есть совсем противоречивые тесты, то пожалуйста выявляейте их в issues, как и предлагает Евгений. А пока можно их и отключить, т.к. наша злодневная задача сейчас это доздать все задания, а чистый набор тестов, это уже просто желаемая фича.
