### ISSUE TITLE
Task 18, class Matrix

### ISSUE THREAD

**Issue by eseev-german** [bmkodoo/javacourses2016#38]
В этом классе логика построена на том, что Width-ширина - это индекс строки, а Height-длина - это индекс столбца, к примеру метод, возвращающий значение элемента:
"public int getValue(int indexWidth, int indexHeight) {
        return matrix[indexWidth][indexHeight];
    }"
Оставить логику такой или допускается изменение этого класса?

**Comment by IvanFefilovTR** [comment]
Это мой недочет когда тест писал должно быть return matrix[indexHeight][indexWidth]; так как это индексы по ширине и высоте соответственно. И в DataProvider'e ошибка, результирующая матрица должна быть только из одинаковых элементов, неправильно понял задание.  Этот класс и тест я добавлял. Все хочу исправить, но еще не разобрался с конфликтами с мастером. Смело можешь менять, исправлять ошибку и кидать обратно на мастер. Остальные методы в этом классе вроде правильные.

**Comment by eseev-german** [comment]
Ок, спасибо за ответ!
