### ISSUE TITLE
Task 18

### ISSUE THREAD

**Issue by PutienkoEN** [bmkodoo/javacourses2016#4]
Не уверен что правильно понимаю задание. К примеру дана матрица 
2 3 4 5
6 7 8 9
7 8 1 1
9 6 1 1

Максимальное число одинаковых элементов 4(единицы), т.е. матрица 
1 1 
1 1
Но так же к примеру подходит матрица
7 8 9
8 1 1
6 1 1

**Comment by nkarulin** [comment]
Разве следующая матрица подходит?

```
7 8 9
8 1 1
6 1 1
```

Ведь в задаче указано: Найти в ней прямоугольную подматрицу, **состоящую из** максимального количества **одинаковых элементов**. А эта матрица состоит из различных эллементов.

**Comment by PutienkoEN** [comment]
Да.. действительно. Я почему-то думал что надо найти **содержащую** максимальное количество элементов.
Теперь все понятно.
