### ISSUE TITLE
Test 17

### ISSUE THREAD

**Issue by eseev-german** [bmkodoo/javacourses2016#46]
I think that third set of values isnt correct, because min abscissa is about 0,9
![image](https://cloud.githubusercontent.com/assets/23452864/21074985/4a870474-bf18-11e6-8aed-4b8a571db1c9.png)

![image](https://cloud.githubusercontent.com/assets/23452864/21074974/067569ba-bf18-11e6-912b-ad2c481cdf68.png)

**Comment by nkarulin** [comment]
Looks right. Thanks!
I disabled this case in master
